version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'shareit-db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=shareit'
    ports:
      - '5432:5432'
    restart: always