CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255),
                                     email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255),
                                     description TEXT,
                                     available BOOLEAN,
                                     owner_id INTEGER,
                                     request_id INTEGER
);

CREATE TABLE IF NOT EXISTS item_requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description TEXT NOT NULL,
                                     requester_id BIGINT NOT NULL,
                                     timestamp TIMESTAMP WITHOUT TIME ZONE
);
