CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255),
                                     email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255),
                                     description TEXT,
                                     available BOOLEAN,
                                     owner_id INTEGER,
                                     request_id INTEGER
);

CREATE TABLE IF NOT EXISTS item_requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description TEXT NOT NULL,
                                     requester_id BIGINT NOT NULL,
                                     timestamp TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     start_date TIMESTAMP WITHOUT TIME ZONE,
                                     end_date TIMESTAMP WITHOUT TIME ZONE,
                                     item_id BIGINT NOT NULL,
                                     booker_id BIGINT NOT NULL,
                                     status VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS comments (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     text TEXT,
                                     item_id BIGINT,
                                     author_id BIGINT,
                                     created TIMESTAMP WITHOUT TIME ZONE
);